[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
[target.wasm32-unknown-unknown]
rustflags = [
#  "-C", "target-feature=+atomics,+bulk-memory",
  "-C", "relocation-model=pic",
]

[target.wasm32-unknown-emscripten]
rustflags = [
#  "-C", "target-feature=+atomics,+bulk-memory",
  "-C", "relocation-model=pic",
#  "-C", "link-args=-rdynamic",
]
